services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-password}"
      POSTGRES_USER: "${DATABASE_USER:-myuser}"
      POSTGRES_DB: "${DATABASE_NAME:-my_portfolio_development}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      args:
        RUBY_VERSION: 3.4.4
    command: bash -lc "bundle install && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: myuser
      DATABASE_PASSWORD: password
      DATABASE_NAME: my_portfolio_development
      RAILS_ENV: development

volumes:
  postgres_data:
